// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/24/2025, 4:35:24 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Nuxt/my-property-status/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/plugins/**/*.{js,ts,mjs}","D:/Nuxt/my-property-status/composables/**/*.{js,ts,mjs}","D:/Nuxt/my-property-status/utils/**/*.{js,ts,mjs}","D:/Nuxt/my-property-status/pages/index.vue","D:/Nuxt/my-property-status/pages/reports.vue","D:/Nuxt/my-property-status/pages/support.vue","D:/Nuxt/my-property-status/pages/agencies.vue","D:/Nuxt/my-property-status/pages/customers.vue","D:/Nuxt/my-property-status/pages/dashboard.vue","D:/Nuxt/my-property-status/pages/admin-users.vue","D:/Nuxt/my-property-status/pages/terms-conditions.vue","D:/Nuxt/my-property-status/pages/send-push-notification.vue","D:/Nuxt/my-property-status/pages/new-connection-requests.vue","D:/Nuxt/my-property-status/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;