// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/7/2025, 8:03:39 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Nuxt/my-property-status/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/plugins/**/*.{js,ts,mjs}","D:/Nuxt/my-property-status/composables/**/*.{js,ts,mjs}","D:/Nuxt/my-property-status/utils/**/*.{js,ts,mjs}","D:/Nuxt/my-property-status/pages/index.vue","D:/Nuxt/my-property-status/pages/admin/reports.vue","D:/Nuxt/my-property-status/pages/admin/support.vue","D:/Nuxt/my-property-status/pages/admin/agencies.vue","D:/Nuxt/my-property-status/pages/admin/what-new.vue","D:/Nuxt/my-property-status/pages/admin/customers.vue","D:/Nuxt/my-property-status/pages/admin/dashboard.vue","D:/Nuxt/my-property-status/pages/agency/dashboard.vue","D:/Nuxt/my-property-status/pages/admin/admin-users.vue","D:/Nuxt/my-property-status/pages/admin/sale-properties.vue","D:/Nuxt/my-property-status/pages/admin/rental-properties.vue","D:/Nuxt/my-property-status/pages/admin/terms-of-services.vue","D:/Nuxt/my-property-status/pages/admin/notification-History.vue","D:/Nuxt/my-property-status/pages/admin/system-notifications.vue","D:/Nuxt/my-property-status/pages/admin/send-push-notification.vue","D:/Nuxt/my-property-status/pages/admin/new-connection-requests.vue","D:/Nuxt/my-property-status/pages/admin/send-email-notification.vue","D:/Nuxt/my-property-status/pages/agency/linked-sale-properties.vue","D:/Nuxt/my-property-status/pages/agency/new-connection-requests.vue","D:/Nuxt/my-property-status/pages/agency/linked-rental-properties.vue","D:/Nuxt/my-property-status/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Nuxt/my-property-status/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;